[profile.default]
solc = "0.8.19"
optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@forge=lib/forge-std/src/",
  "@solady=lib/solady/"
]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"